name: Create Nightly Release

on:
  push:
    branches:
      - main

jobs:

  build_mac_job:
    runs-on: [self-hosted, macOS]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Bootstrap environment
      run: ./bin/macos/bootstrap.sh

    - name: Clean Workspace
      run: ./bin/macos/clean.sh

    - name: Build Binary
      run: ./bin/macos/build.sh

    - name: Make DMG
      run: ./bin/macos/make_dmg.sh

    - name: Upload Release Asset
      id: upload-release-asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        repo_name: gshau/TheAstroImagingPlanner
        file: ./dist/AstroImagingPlanner.dmg
        asset_name: AstroImagingPlanner-MacOS-latest.dmg
        tag: latest-${{ github.ref_name }}
        release_name: latest-${{ github.ref_name }}
        overwrite: true
        body: "Nightly release"
  
  build_windows_job:
    runs-on: [self-hosted, windows, x64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Bootstrap
        run: .\bin\windows\bootstrap.bat

      - name: Clean
        run: .\bin\windows\clean.bat

      - name: Build
        run: .\bin\windows\build.bat

    - name: Upload Release Asset
      id: upload-release-asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        repo_name: gshau/TheAstroImagingPlanner
        file: '.\build_assets\windows\installers\Install AstroImaging Planner.exe'
        asset_name: 'Install_AstroImagingPlanner-Windows-latest.exe'
        tag: latest-${{ github.ref_name }}
        release_name: latest-${{ github.ref_name }}
        overwrite: true
        body: "Nightly release"
